In [ ]:
# question 3
# A school method based Python3
# program to check if a number
# is prime

def prime(n):

	# Corner case
	if n <= 1:
		return False

	# Check from 2 to n-1
	for i in range(2, n):
		if n % i == 0:
			return False;

	return True


import numpy as np
s=[]
a=int(input("Enter the length of the array"))
row=int(input('Enter the number of rows: '))
col=int(input("enter the number of column: "))
for i in range(a):
    s.append(int(input("Enter the number")))
m=np.array(s)
m = m.reshape(row,col)
count=0
add=0
for i in range(row):
    for j in range(col):
        if prime(count):
            add=add+m[i][j]+(m[i][j])**3
            m[i][j]=(m[i][j])**3
        count+=1
print(m)
print(add) 

In [ ]:
import numpy as np
a=int(input('Enter the length of first array: '))
b=int(input('Enter the length of the second array: '))
c=[]
d=[]
for i in range(a):
    c.append(int(input('Enter the number: ')))
for i in range(b):
    d.append(int(input('Enter the number: ')))
m=np.array(c)
n=np.array(d)
common_elements = np.intersect1d(m, n)
print(common_elements)



In [15]:
#
import numpy as np
a=np.arange(7,344,7)
a=a.reshape(7,7)
print(a)
print (a[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


In [271]:
import string
import random

a=''
for i in range(2):
    a+=random.choice(string.ascii_lowercase)
    a+=random.choice(string.digits)
a+=random.choice(string.ascii_uppercase)
a+=random.choice(string.punctuation)
print(a)
j=[]
for i in range(len(a)):
    j.append(a[i])
random.shuffle(j)
print(j)
    

v1s9Z>
['1', 'Z', 's', 'v', '9', '>']


In [290]:
import numpy as np
a=np.ones((7,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [1]:
import numpy as np
a,b=int(input('Enter the number of rows')),int(input("Enter the number of columns"))
arr=np.zeros((a,b),dtype='int16')
for i in range(a):
    for j in range(b):
        if i%2==0 and j%2==0:
            arr[i][j]=1
        elif i%2!=0 and j%2!=0:
            arr[i][j]=1
print(arr)

Enter the number of rows5
Enter the number of columns5
[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [ ]:
import string
# a=np.array(list(string.ascii_uppercase)[:-2]).reshape(6,4)
a=list(string.ascii_uppercase)
for i in range(len(a)):
    if a[i]=="A" or a[i]=="E" or a[i]=="I" or a[i]=="O" or a[i]=="U":
        a[i]=np.nan

print(a)
